name: Auto approve and merge PRs by dependabot

# Trigger the workflow on pull request
on:
  pull_request:
    branches:
      - 'infra/dependabot'

jobs:
  autoapprove:
    name: Auto Approve a PR by dependabot # Name of the job
    runs-on: ubuntu-latest # Environment on which the job runs
    steps:
      - uses: hmarr/auto-approve-action@v3

      - run: npm ci
      - name: Pull request number
        run: |
          echo "Pull Request Number - ${{ github.event.pull_request.number }}"
