name: AutoAprrove

on:
  pull_request

jobs:
  autoapprove:
    runs-on: ubuntu-latest
    name: Auto Approve a PR by dependabot
    permissions:
      pull-requests: write
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}

  automerge:
    name: Auto merge after successful checks
    # By default, jobs run in parallel. To run the jobs sequentially, they keywords "needs" is needed.
    # Auto merge action can be done only when the PR is approved, hence this automerge needs autoapprove as a prerequisite
    needs: autoapprove
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.mytoken }}