name: AutoAprrove

on:
  pull_request_target:
    branches:
      - infra/dependabot

jobs:
  autoapprove:
    runs-on: ubuntu-latest
    name: Auto Approve a PR by dependabot
    permissions:
      pull-requests: write
    steps:
      - run: echo "hello world" # run the `echo` command
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.AUTO_APPROVE_TOKEN }}